services:
  - type: web
    name: fras-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker wsgi:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fras-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
      - key: ALLOWED_ORIGINS
        value: "https://frontends-weld.vercel.app"
databases:
  - name: fras-db
    databaseName: fleetdb
    user: frasuser
